Repository COSIMA/cosima-recipes, pull requests merged in 2022-11, with the labels that each got.

#163 Example of Gadi PBS Analysis Script submission
  Tutorials/Submitting_analysis_jobs_to_gadi.ipynb
Labels: tutorial

#168 Adds icon for `Submitting job to gadi` tutorial
  Tutorials/Submitting_analysis_jobs_to_gadi.ipynb
  Tutorials/assets/gadi.png
Labels: updating

#166 Updates the map tutorial
  Tutorials/Making_Maps_with_Cartopy.ipynb
Labels: updating

#171 Simpler Tutorial section title
  Tutorials/README.rst
Labels: cleanup

#167 Update the example notebook template
  DocumentedExamples/SeaIceSeasonality_DFA.ipynb
  Tutorials/Template_For_Notebooks.ipynb
Labels: updating

#176 Updates ` COSIMA_CookBook_Tutorial.ipynb`
  DocumentedExamples/True_Zonal_Mean.ipynb
  Tutorials/COSIMA_CookBook_Tutorial.ipynb
Labels: updating

#172 Add `use_cftime=True` in sea ice example
  DocumentedExamples/SeaIceSeasonality_DFA.ipynb
Labels: bug, updating

#169 Update True Zonal Mean notebook
  DocumentedExamples/True_Zonal_Mean.ipynb
Labels: updating

#158 New Documented example: Cross-contour transport
  DocumentedExamples/Cross-contour_transport.ipynb
  DocumentedExamples/images/contour_schematic.png
Labels: enhancement
