Repository COSIMA/cosima-recipes, pull requests merged in 2023-02, with the labels that each got.

#217 Modifying zonally averaged overturning to be model agnostic
  DocumentedExamples/Zonally_Averaged_Global_Meridional_Overturning_Circulation.ipynb
Labels: 💻 hackathon 2.0, MOM5+MOM6 ❤️

#242 Update comparison of SSH model+output example
  .jenkins/Jenkinsfile
  DocumentedExamples/Compare_SSH_model_obs.ipynb
  test/test_notebooks.py
Labels: 🛸 updating, testing 🧪

#228 Barotropic Streamfunction model agnostic
  DocumentedExamples/Barotropic_Streamfunction.ipynb
  DocumentedExamples/Barotropic_Streamfunction_model_agnostic.ipynb
  test/test_notebooks.py
Labels: 💻 hackathon 2.0, MOM5+MOM6 ❤️

#248 Example to calculate geostrophic velocities from simulated sea level.
  DocumentedExamples/Geostrophic_Velocities_from_Sea_Level.ipynb
Labels: 🧜🏽‍♀️ enhancement, 💻 hackathon 2.0

#250 Update transport through straits notebook + use `pint`
  DocumentedExamples/Transport_Through_Straits.ipynb
  test/test_notebooks.py
Labels: 🛸 updating

#247 Merging two documented examples and correcting bugs
  DocumentedExamples/Annually_Averaged_Scalar_Timeseries.ipynb
  DocumentedExamples/Querying_Scalar_Quantities.ipynb
  DocumentedExamples/Querying_Scalar_Quantities_and_Annually_Averaged_Timeseries.ipynb
  test/test_notebooks.py
Labels: 🛸 updating, 🧹 cleanup, 💻 hackathon 2.0
