Repository COSIMA/cosima-recipes, pull requests merged in 2023-01, with the labels that each got.

#183 Simplifies bathymetry example
  ContributedExamples/Bathymetry.ipynb
Labels: 🧹 cleanup

#218 Add Jenkins test checking that notebooks run correctly
  .jenkins/Jenkinsfile
  README.md
  test/test_notebooks.py
Labels: technical, 💻 hackathon 2.0, testing 🧪

#223 Added new Documented Bathymetry notebook with Blue Marble example
  DocumentedExamples/Bathymetry.ipynb
Labels: 💻 hackathon 2.0

#231 New documentation for Documented bathymetry example and delete Contributed bathymetry example
  ContributedExamples/Bathymetry.ipynb
  DocumentedExamples/Bathymetry.ipynb
Labels: 🛸 updating, 💻 hackathon 2.0

#232 Include bathymetry documented example in tests
  test/test_notebooks.py
Labels: 💻 hackathon 2.0, testing 🧪

#227 Promote Meridional Heat Transport example into Documented Examples
  ContributedExamples/plot_mht.ipynb
  DocumentedExamples/meridional_heat_transport.ipynb
Labels: 💻 hackathon 2.0

#170 Delete `sandbox`: it's time to let go broken code
  README.md
  sandbox/APE-MOM Figures.ipynb
  sandbox/CC_WindStress_Curl.ipynb
  sandbox/Ice Validation mom025.ipynb
  sandbox/MOM-SIS-01 Salinity Restoring Analysis.ipynb
  sandbox/MOM01_SaltEval.ipynb
  sandbox/MOM01_TempEval.ipynb
  sandbox/Monitor_model_stability_using_vertical_wbt.ipynb
  sandbox/README.md
  sandbox/RYF_Analysis.ipynb
  sandbox/plot_mld.ipynb
  sandbox/plot_sst_pac.ipynb
  sandbox/plot_surface_current.ipynb
  sandbox/u_seasonal_cycle_ind_eq.ipynb
Labels: 🧹 cleanup, 💻 hackathon 2.0

#226 Model agnostic tutorial
  Tutorials/Model_Agnostic_Analysis.ipynb
Labels: 📔 tutorial, 💻 hackathon 2.0, MOM5+MOM6 ❤️

#235 Add MHT estimate from the surface heat flux
  DocumentedExamples/Meridional_heat_transport.ipynb
Labels: 🛸 updating

#238 MHT example: clean up imports + evaluate fig cell
  DocumentedExamples/Meridional_heat_transport.ipynb
Labels: 🛸 updating, 🧹 cleanup

#224 Confirms that some documented examples work, added minor things
  DocumentedExamples/Age_at_the_Bottom.ipynb
  DocumentedExamples/Atlantic_IndoPacific_Basin_Overturning_Circulation.ipynb
  DocumentedExamples/Barotropic_Streamfunction.ipynb
  DocumentedExamples/Binning_transformation_from_depth_to_potential_density.ipynb
Labels: 💻 hackathon 2.0

#240 Update regridding example
  DocumentedExamples/Regridding.ipynb
  test/test_notebooks.py
Labels: 🛸 updating

#239 Add more examples in tests
  test/test_notebooks.py
Labels: testing 🧪

#236 Add example notebook for particle tracking with ACCESS-OM2-01
  DocumentedExamples/Particle_tracking_with_Parcels.ipynb
Labels: 🧜🏽‍♀️ enhancement, 💻 hackathon 2.0

#243 Add TemperatureSalinityDiagrams.ipynb example that works for MOM5 and MOM6
  DocumentedExamples/TemperatureSalinityDiagrams_mom5_mom6.ipynb
Labels: 💻 hackathon 2.0, MOM5+MOM6 ❤️

#244 Update tests
  .jenkins/Jenkinsfile
  test/test_notebooks.py
Labels: testing 🧪
