Repository COSIMA/cosima-recipes, pull requests merged in 2023-10, with the labels that each got.

#283 Fix SST/SSS WOA13 comparison and equatorial thermal/zonal velocity examples
  DocumentedExamples/Compare_SST_SSS_TemperatureSalinity_to_WOA13.ipynb
  DocumentedExamples/Equatorial_thermal_and_zonal_velocity_structure.ipynb
  DocumentedExamples/Zonally_Averaged_Global_Meridional_Overturning_Circulation.ipynb
  test/test_notebooks.py
Labels: 🎮 hackathon 3.0

#293 Update kernels for Relative Vorticity example
  DocumentedExamples/RelativeVorticity.ipynb
Labels: 🛸 updating

#299 Jenkins failures
  .jenkins/Jenkinsfile
  README.md
  Tutorials/Model_Agnostic_Analysis.ipynb
  Tutorials/Using_Explorer_tools.ipynb
  test/README.md
  test/test_notebooks.py
Labels: testing 🧪

#303 Reduce toctree level for notebook galleries
  .github/workflows/sphinx.yml
  docs/documented_examples.rst
  docs/tutorials.rst
Labels: 🛸 updating, documentation 📜

#292 Fix bug in `mask_numbered`
  DocumentedExamples/Cross-contour_transport.ipynb
Labels: 🐞 bug

#304 Typo in test_notebooks.py
  test/test_notebooks.py
Labels: testing 🧪

#305 Fix regrid example
  DocumentedExamples/Regridding.ipynb
Labels: 🛸 updating

#284 Remapped overturning into depth space, masked the mediteranean in mom5
  DocumentedExamples/Zonally_Averaged_Global_Meridional_Overturning_Circulation.ipynb
Labels: 🎮 hackathon 3.0
