Repository COSIMA/cosima-recipes, pull requests merged in 2024-09, with the labels that each got.

#359 Intake conversion Equatorial_thermal_and_zonal_velocity_structure
  Recipes/Equatorial_thermal_and_zonal_velocity_structure.ipynb
Labels: 🕹️ hackathon 4.0

#453 Simplify Sea_ice_seasonality
  Recipes/Sea_Ice_Seasonality_Statistics.ipynb
Labels: 🛸 updating

#452 Add movie tutorial with xmovie package
  Tutorials/Animations_with_xmovie.ipynb
  Tutorials/movie_sst.gif
Labels: 📔 tutorial, 🐣 new recipe

#455 Add coastlines in animation tutorial
  Tutorials/Animations_with_xmovie.ipynb
  Tutorials/movie_sst.gif
Labels: 🧜🏽‍♀️ enhancement

#456 Fix typo in Intake tutorial
  Tutorials/ACCESS-NRI_Intake_Catalog.ipynb
Labels: 📔 tutorial

#457 Convert first person singular to first person plural in a recipe
  Recipes/Atlantic_IndoPacific_Basin_Overturning_Circulation.ipynb
Labels: ready to review ❣️
