Repository COSIMA/cosima-recipes, pull requests merged in 2024-07, with the labels that each got.

#401 Resolve ssh ambiguity in cookbook tutorial
  Tutorials/COSIMA_CookBook_Tutorial.ipynb
Labels: 🛸 updating

#372 Intake conversion Transport_Through_Straits
  DocumentedExamples/Transport_Through_Straits.ipynb
Labels: 🕹️ hackathon 4.0

#399 Updates temperature hovmoller example to use latest version of the cosima cookbook
  ContributedExamples/Hovmoller_Temperature_Depth.ipynb
  DocumentedExamples/Hovmoller_Temperature_Depth.ipynb
Labels: 🛸 updating

#404 Urge users towards Intake catalog rather than cookbook
  README.md
  Tutorials/ACCESS-NRI_Intake_Catalog.ipynb
  Tutorials/COSIMA_CookBook_Tutorial.ipynb
Labels: documentation 📜, 🕹️ hackathon 4.0

#408 Update README.md after deleting contributed examples
  README.md
  docs/conf.py
  docs/examples.rst
  docs/index.rst
Labels: documentation 📜

#410 Fix link in docs/index.rst
  docs/index.rst
Labels: documentation 📜

#411 Minor tweaks in example titles etc
  Examples/Binning_transformation_from_depth_to_potential_density.ipynb
  Examples/Particle_tracking_with_Parcels.ipynb
Labels: 🧹 cleanup

#380 Intake conversion Submitting_analysis_jobs_to_gadi
  Tutorials/Submitting_analysis_jobs_to_gadi.ipynb
Labels: 🕹️ hackathon 4.0

#381 Intake conversion Template_For_Notebooks
  Tutorials/Template_For_Notebooks.ipynb
Labels: 🕹️ hackathon 4.0

#396 Add to pr reviewing instructions
  docs/contributing.rst
Labels: documentation 📜, 🕹️ hackathon 4.0

#322 Enhance MHT example
  Examples/Meridional_heat_transport.ipynb
Labels: 🛸 updating, 🧹 cleanup, performance 🏎️, 🕹️ hackathon 4.0

#354 Intake conversion Compare_SSH_model_obs
  Examples/Compare_SSH_model_obs.ipynb
Labels: 🕹️ hackathon 4.0

#345 Intake conversion Fig4-DrakePassageTransport
  ACCESS-OM2-GMD-Paper-Figs/Fig4-DrakePassageTransport.ipynb
Labels: 🕹️ hackathon 4.0

#415 Remove cookbooks reference and tidy
  Tutorials/Template_For_Notebooks.ipynb
Labels: 🧹 cleanup

#352 Intake conversion Bathymetry
  Examples/Bathymetry.ipynb
Labels: 🕹️ hackathon 4.0

#360 Intake conversion Geostrophic_Velocities_from_Sea_Level
  Examples/Geostrophic_Velocities_from_Sea_Level.ipynb
Labels: 🕹️ hackathon 4.0

#379 Intake conversion Spatial_selection
  Tutorials/Spatial_selection.ipynb
Labels: 🕹️ hackathon 4.0

#413 Intake conversion Regridding example; take #2
  Examples/Horizontal_Regridding.ipynb
  Examples/Regridding.ipynb
Labels: 🛸 updating

#430 Bit of cleanup Submitting_analysis_jobs_to_gadi.ipynb
  Tutorials/Submitting_analysis_jobs_to_gadi.ipynb
Labels: 🧹 cleanup

#417 Created neutral density example notebook
  Examples/Neutral_density.ipynb
Labels: 🐣 new example, 🕹️ hackathon 4.0

#428 Updated Barotropic_streamfunction
  Examples/Barotropic_Streamfunction.ipynb
Labels: 🛸 updating

#349 Intake conversion Extract_variables_at_ocean_bottom
  Examples/Extract_Variables_at_Ocean_Bottom.ipynb
Labels: 🕹️ hackathon 4.0

#431 Incorporate "Bathymetry" recipe in the "Making maps w Cartopy" tutorial
  Examples/Bathymetry.ipynb
  Tutorials/Making_Maps_with_Cartopy.ipynb
Labels: 🧹 cleanup, 📔 tutorial, ready to review ❣️

#426 Intake conversion of `Relative_Vorticity`; take #2
  Examples/RelativeVorticity.ipynb
  Examples/Relative_Vorticity.ipynb
Labels: 🛸 updating, ready to review ❣️

#423 Fix bugs in Cross-contour_transport take 2
  Examples/Cross-contour_transport.ipynb
Labels: 🐞 bug, 🕹️ hackathon 4.0
