Repository COSIMA/cosima-recipes, pull requests merged in 2024-08, with the labels that each got.

#436 Rebrand leftovers
  README.md
  docs/_static/thumbnails/intake.png
  docs/contributing.rst
Labels: documentation 📜

#344 Intake conversion Fig3-GlobalTimeseries
  ACCESS-OM2-GMD-Paper-Figs/Fig3-GlobalTimeseries.ipynb
Labels: 🕹️ hackathon 4.0

#438 Less cookbook, more intake
  README.md
Labels: documentation 📜

#421 Add example of `apply_ufunc`
  Recipes/Apply_function_to_every_gridpoint.ipynb
Labels: 🕹️ hackathon 4.0

#420 Simplified examples for plotting cross-section and along slope velocity
  Recipes/Along-slope-velocities.ipynb
  Recipes/Cross-slope_section.ipynb
Labels: 🛸 updating, 🕹️ hackathon 4.0, ready to review ❣️

#324 Towards model agnosticism + pint functionality in Meridional Overturning Circulation example
  Recipes/Meridional_Overturning_Circulation.ipynb
Labels: 🛸 updating, 🧹 cleanup, MOM5+MOM6 ❤️, performance 🏎️, 🕹️ hackathon 4.0

#338 Add example of regional configuration using regional-mom6 package forced with ACCESS-OM2-01
  Recipes/regional-mom6-forced-by-access-om2.ipynb
Labels: 🐣 new example

#365 Intake conversion Querying_Scalar_Quantities_and_Annually_Averaged_Timeseries
  Recipes/Querying_Scalar_Quantities_and_Annually_Averaged_Timeseries.ipynb
Labels: 🕹️ hackathon 4.0

#358 Intake conversion Decomposing_kinetic_energy_into_mean_and_transient
  Recipes/Decomposing_kinetic_energy_into_mean_and_transient.ipynb
Labels: 🕹️ hackathon 4.0

#346 Intake conversion Figs14-20-23-24-PlotWOCETransects
  ACCESS-OM2-GMD-Paper-Figs/Figs14-20-23-24-PlotWOCETransects.ipynb
Labels: 🕹️ hackathon 4.0

#363 Intake conversion NearestNeighbourDistance
  Recipes/Nearest_Neighbour_Distance.ipynb
Labels: 🕹️ hackathon 4.0, ready to review ❣️
