Repository COSIMA/cosima-recipes, pull requests merged in 2025-06, with the labels that each got.

#525 Update regional recipe to work with regional-mom6 v1.0.1
  Recipes/regional-mom6-forced-by-access-om2.ipynb
Labels: 🛸 updating

#530 Remove dask clutter + drop gdata
  Recipes/regional-mom6-forced-by-access-om2.ipynb
Labels: 🧹 cleanup

#529 Categorise recipes + rename recipes and tutorials to dishes and cooking lessons
  README.md
  Recipes/appetisers-easy/Atlantic_IndoPacific_Basin_Overturning_Circulation.ipynb
  Recipes/appetisers-easy/Barotropic_Streamfunction.ipynb
  Recipes/appetisers-easy/Compare_SSH_model_obs.ipynb
  Recipes/appetisers-easy/Compare_SST_SSS_TemperatureSalinity_to_WOA13.ipynb
  Recipes/appetisers-easy/Hovmoller_Temperature_Depth.ipynb
  Recipes/appetisers-easy/Meridional_Overturning_Circulation.ipynb
  Recipes/appetisers-easy/Model_Resolution_Comparison.ipynb
  Recipes/appetisers-easy/Querying_Scalar_Quantities_and_Annually_Averaged_Timeseries.ipynb
  Recipes/appetisers-easy/Relative_Vorticity.ipynb
  Recipes/appetisers-easy/Transport_Through_Straits.ipynb
  Recipes/appetisers-easy/True_Zonal_Mean.ipynb
  Recipes/local-dishes-regional/regional-mom6-forced-by-access-om2.ipynb
  Recipes/mains-advanced/Along-slope-velocities.ipynb
  Recipes/mains-advanced/Along_Isobath_Average.ipynb
  Recipes/mains-advanced/Cross-contour_transport.ipynb
  Recipes/mains-advanced/Cross-slope_section.ipynb
  Recipes/mains-advanced/Eddy-Mean_Kinetic_Energy_Decomposition.ipynb
  Recipes/mains-advanced/Equatorial_thermal_and_zonal_velocity_structure.ipynb
  Recipes/mains-advanced/Extract_Variables_at_Ocean_Bottom.ipynb
  Recipes/mains-advanced/Geostrophic_Velocities_from_Sea_Level.ipynb
  Recipes/mains-advanced/Horizontal_Regridding.ipynb
  Recipes/mains-advanced/Meridional_heat_transport.ipynb
  Recipes/mains-advanced/Nearest_Neighbour_Distance.ipynb
  Recipes/mains-advanced/Neutral_density.ipynb
  Recipes/mains-advanced/Particle_tracking_with_Parcels.ipynb
  Recipes/mains-advanced/Sea_Ice_Area_Concentration_Volume_with_Obs.ipynb
  Recipes/mains-advanced/Sea_Ice_Coordinates.ipynb
  Recipes/mains-advanced/Sea_Ice_Seasonality_Statistics.ipynb
  Recipes/mains-advanced/Surface_Water_Mass_Transformation.ipynb
  Recipes/mains-advanced/Temperature_Salinity_Diagram.ipynb
  Recipes/mains-advanced/Transformation_from_Depth_to_Potential_Density.ipynb
  docs/conf.py
  docs/guidelines.rst
  docs/index.rst
  docs/recipes.rst
  docs/recipes/appetisers.rst
  docs/recipes/index.rst
  docs/recipes/local-dishes.rst
  docs/recipes/mains.rst
  docs/tutorials.rst
Labels: documentation 📜

#378 Intake conversion Model_Agnostic_Analysis
  Cooking-Lessons-101-Tutorials/Model_Agnostic_Analysis.ipynb
Labels: 🕹️ hackathon 4.0

#355 Intake conversion Compare_SST_SSS_TemperatureSalinity_to_WOA13
  Recipes/Appetisers-Easy/Compare_SST_SSS_TemperatureSalinity_to_WOA13.ipynb
Labels: 🕹️ hackathon 4.0
