Repository COSIMA/cosima-recipes, pull requests merged in 2025-09, with the labels that each got.

#605 Delete 4 old, non-pedagogical recipes
  Cooking-Lessons-101-Tutorials/Template_For_Notebooks.ipynb
  Recipes/Appetisers-Easy/Model_Resolution_Comparison.ipynb
  Recipes/Appetisers-Easy/Querying_Scalar_Quantities_and_Annually_Averaged_Timeseries.ipynb
  Recipes/Mains-Advanced/Equatorial_thermal_and_zonal_velocity_structure.ipynb
Labels: 🧹 cleanup

#562 Move contents of `ACCESS-OM2-GMD-Paper-Figs` in its own repo
  ACCESS-OM2-GMD-Paper-Figs/Fig12-ZonalTempSaltBias.ipynb
  ACCESS-OM2-GMD-Paper-Figs/Fig3-GlobalTimeseries.ipynb
  ACCESS-OM2-GMD-Paper-Figs/Fig4-DrakePassageTransport.ipynb
  ACCESS-OM2-GMD-Paper-Figs/Figs14-20-23-24-PlotWOCETransects.ipynb
  ACCESS-OM2-GMD-Paper-Figs/aravg.ann.ocean.90S.90N.v4.0.1.201901.asc
  ACCESS-OM2-GMD-Paper-Figs/exptdata.py
  README.md
Labels: 🧹 cleanup

#608 Remove deprecated `cosima_cookbook` references from ACCESS-NRI catalog tutorial
  01-Cooking-Lessons-101/01-Basics/02-ACCESS-NRI_Intake_Catalog.ipynb
Labels: 🛸 updating, 📔 tutorial

#617 Convert Barotropic Streamfunction recipe to use only MOM6
  .zenodo.json
  02-Appetisers/Barotropic_Streamfunction.ipynb
Labels: 🎏 hackathon 5.0
