Repository COSIMA/cosima-recipes, pull requests merged in 2025-02, with the labels that each got.

#482 Add demo on how to get all info about variables
  Tutorials/ACCESS-NRI_Intake_Catalog.ipynb
Labels: 📔 tutorial

#402 Convert the Surface Water Mass Transformation example to be model-agnostic
  Recipes/Surface_Water_Mass_Transformation.ipynb
Labels: 🛸 updating, MOM5+MOM6 ❤️, 🕹️ hackathon 4.0

#486 Dask client with `threads_per_worker=1` in parcels recipe
  Recipes/Particle_tracking_with_Parcels.ipynb
Labels: 🐞 bug
